{% set name = "voila-material" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05a86ad2bf0a9b1004ab260d9c90494f6b6e7c6fb198a0e952bf76708ee6f485

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3
    - pip
  run:
    - python >3
    - voila >=0.1.12,<0.2

test:
  commands:
    - test -d ${PREFIX}/share/jupyter/voila/templates/material  # [unix]
    - test -f ${PREFIX}/share/jupyter/voila/templates/material/nbconvert_templates/voila.tpl  # [unix]
    - if exist %LIBRARY_PREFIX%\\..\\share\\jupyter\\voila\\templates\\material\\nbconvert_templates\\voila.tpl (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/voila-dashboards/voila-material
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Material template for Voila
  dev_url: https://github.com/voila-dashboards/voila-material

extra:
  recipe-maintainers:
    - martinRenou
